// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_code, original_url)
VALUES ($1, $2)
    RETURNING id, short_code, original_url, access_count, created_at, updated_at
`

type CreateURLParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURLByShortCode = `-- name: DeleteURLByShortCode :exec
DELETE FROM urls
WHERE short_code = $1
`

func (q *Queries) DeleteURLByShortCode(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, deleteURLByShortCode, shortCode)
	return err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, original_url, access_count, created_at, updated_at
FROM urls
WHERE short_code = $1 LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAccessCount = `-- name: IncrementAccessCount :exec
UPDATE urls
SET access_count = access_count + 1,
    updated_at = NOW()
WHERE short_code = $1
`

func (q *Queries) IncrementAccessCount(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementAccessCount, shortCode)
	return err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET original_url = $1,
    updated_at = NOW()
WHERE short_code = $2
RETURNING id, short_code, original_url, access_count, created_at, updated_at
`

type UpdateURLParams struct {
	OriginalUrl string
	ShortCode   string
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURL, arg.OriginalUrl, arg.ShortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.AccessCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
